---
title: "Supporting nice tables for Q reviews or Outlays"
author: adapted from"jdavis"
date: "1/4/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


We'll be reproducing the table located here:
https://docs.google.com/presentation/d/1tR3a81fd5mtkAX-RkX3hZv7skahkHryIrbrI7mli1Pc/edit#slide=id.p6


T
## Libraries + globals
  
```{r}
library(tidyverse)
library(glamr)
#install.packages("gt")
library(gt)
library(googledrive)
library(googlesheets4)
library(ICPIutilities)
library(glitr)
library(RColorBrewer)
library(scales)
library(dplyr)
library(extrafont)
library(scales)
library(tidytext)
library(patchwork)
library(ggtext)
library(glue)
library(janitor)
library(lubridate)
library(patchwork)


pal <- RColorBrewer::brewer.pal(5, "Spectral")[2:4] ## we'll come back to this
save_path <- "2021-01-18"

```
  
##munging your data
  We're going to look at a simple table that's in long format and convert to wide using `pivot_wider
  
```{r}
## load Outlay File
 df<-read.csv("Data/Q2 Outlay-Moz (Overall).csv")
  df<-df%>%
      dplyr::rename("COP 20 Budget" = COP20.Planned.Funding,
                    "Mechanism Name"=MECHANISM.NAME,
                    "Prime Partner Name"=IMPLEMENTING.MECHANISM,
                    "Q1 Outlays"= Q1.Outlays,
                    "Q2 Outlays"= Q2.Outlays,
                    "Outlay Perct."=X.Outlayed,
                    "Total Outlays"=Total.Outlays)
 
#df <-df %>% drop_na(`COP 20 Budget`)

#CIPs
df1<-df%>%
   filter(Mechanism.ID  %in% c("70212", "81790", "81791","84608","81806","80032"))

df_Over<-df%>%
  filter(`Outlay Perct.`>.6)


```

```{r}
#CIP table
tbl<-df1 %>%
   dplyr::select(-`Prime Partner Name`,-Mechanism.ID,-Undisbursed)%>%
  dplyr::relocate(`COP 20 Budget`, .after = `Total Outlays`)%>%
  arrange(desc(`Outlay Perct.`))%>% # sort by outlay %
  gt()%>%
  fmt_missing(columns = everything(),
            missing_text = "-")%>%
  fmt_percent(
   columns = vars(`Outlay Perct.`),
  decimals = 0)%>%
   fmt_currency( # add dolar signs
    columns = vars(`COP 20 Budget`, "Q1 Outlays", "Q2 Outlays", `Total Outlays`),
    decimals = 0,
    currency = "USD")%>%
  
   tab_options(
    table.font.names = "Source Sans Pro"
    ) %>% 
   cols_width(
    everything() ~ px(110))%>%
    tab_spanner(
    label = "COP20 Outlays",
    columns = c( "Q1 Outlays", "Q2 Outlays","Total Outlays"))%>%
  
  tab_style(style = cell_fill(color ="#ffcaa2"),      ## defining the what (the 4th value of the pal object)
              locations = cells_body(                 ## telling it where (ie, the body of a cell)
                columns = vars(`Outlay Perct.`),      ## which col this refers to (note `vars()`)
                rows = `Outlay Perct.` >= .6)) %>%   ## the argument   ## using Q2 colors here
    #tab_style(style = cell_fill(color = "#5bb5d5"),
     #         locations = cells_body(
      #          columns = vars(`Outlay Percentage`),
       #         rows = `Outlay Percentage` < .6)) %>% 
    tab_style(style = cell_fill(color ="#ff939a"  ),
              locations = cells_body(
                columns = vars(`Outlay Perct.`),
                rows = `Outlay Perct.` < .34)) %>% 
 tab_header(title = "USAID Clinical IP Outlays Through FY21 Q2") %>% 
  tab_source_note("Source: USAID Phoenix Financial System May 2021")%>%
  tab_footnote(footnote = "Includes new funding and applied pipeline.",
    locations = cells_column_labels(columns = "COP 20 Budget"))%>%
  
  tab_footnote(
    footnote = "ECHO under-outlay due to delayed vouchering and submission of payments.",
    locations = cells_body(columns = "Mechanism Name", rows = 1))%>%
   tab_style(
    style = cell_borders(
      sides = "right",
      weight = px(1.5),
    ),
    locations = cells_body(
      columns = everything(),
      rows = everything()
    ))
  
tbl%>%gtsave("Clinical IP table.png")
gtsave(tbl, ("corps_table.PNG"), zoom = 1)

```

```{r}
#undisbursed
tbl2<-df %>%
   dplyr::select(-`Prime Partner Name`,-Mechanism.ID)%>%
  dplyr::relocate(`COP 20 Budget`, .after = `Total Outlays`)%>%
  arrange(desc(`Undisbursed`))%>%
  top_n(11)%>%# sort by outlay %
  gt()%>%
  fmt_missing(columns = everything(),
            missing_text = "-")%>%
  fmt_percent(
   columns = vars(`Outlay Perct.`),
  decimals = 0)%>%
   fmt_currency( # add dolar signs
    columns = vars(`COP 20 Budget`, "Q1 Outlays", "Q2 Outlays", `Total Outlays`, `Undisbursed`),
    decimals = 0,
    currency = "USD")%>%
  
   tab_options(
    table.font.names = "Source Sans Pro"
    ) %>% 
   cols_width(
    everything() ~ px(110))%>%
    tab_spanner(
    label = "COP20 Outlays",
    columns = c( "Q1 Outlays", "Q2 Outlays","Total Outlays"))%>%
  
  tab_style(style = cell_fill(color ="#ffcaa2"),      ## defining the what (the 4th value of the pal object)
              locations = cells_body(                 ## telling it where (ie, the body of a cell)
                columns = vars(`Outlay Perct.`),      ## which col this refers to (note `vars()`)
                rows = `Outlay Perct.` >= .6)) %>%   ## the argument   ## using Q2 colors here
    #tab_style(style = cell_fill(color = "#5bb5d5"),
     #         locations = cells_body(
      #          columns = vars(`Outlay Percentage`),
       #         rows = `Outlay Percentage` < .6)) %>% 
    tab_style(style = cell_fill(color ="#ff939a"  ),
              locations = cells_body(
                columns = vars(`Outlay Perct.`),
                rows = `Outlay Perct.` < .6)) %>% 
   tab_style((cell_text(style = "italic") ),
              locations = cells_body(
                columns = everything(),
                rows = 1))%>%
 tab_header(title = "USAID Top 10 Mechanisms By Remaining Funds") %>% 
  tab_source_note("Source: USAID Phoenix Financial System May 2021")%>%
  tab_footnote(footnote = "Includes new funding and applied pipeline.",
    locations = cells_column_labels(columns = "COP 20 Budget"))%>%
  
  tab_footnote(
    footnote = "ECHO under-outlay due to delayed vouchering and submission of payments.",
    locations = cells_body(columns = "Mechanism Name", rows = 2))%>%
   tab_style(
    style = cell_borders(
      sides = "right",
      weight = px(1.5),
    ),
    locations = cells_body(
      columns = everything(),
      rows = everything()
    ))
```  
tbl2%>%gtsave("Undispursed table.png")
gtsave(tbl, ("corps_table.PNG"), zoom = 1)

````{r}
#over 60%
tbl3<-df_Over %>%
   dplyr::select(-`Prime Partner Name`,-Mechanism.ID, -`Undisbursed`)%>%
  dplyr::relocate(`COP 20 Budget`, .after = `Total Outlays`)%>%
  arrange(desc(`Outlay Perct.`))%>%
  #top_n(11)%>%# sort by outlay %
  gt()%>%
  fmt_missing(columns = everything(),
            missing_text = "-")%>%
  fmt_percent(
   columns = vars(`Outlay Perct.`),
  decimals = 0)%>%
   fmt_currency( # add dolar signs
    columns = vars(`COP 20 Budget`, "Q1 Outlays", "Q2 Outlays", `Total Outlays`),
    decimals = 0,
    currency = "USD")%>%
  
   tab_options(
    table.font.names = "Source Sans Pro"
    ) %>% 
   cols_width(
    everything() ~ px(110))%>%
    tab_spanner(
    label = "COP20 Outlays",
    columns = c( "Q1 Outlays", "Q2 Outlays","Total Outlays"))%>%
  
  tab_style(style = cell_fill(color ="#ffcaa2"),      ## defining the what (the 4th value of the pal object)
              locations = cells_body(                 ## telling it where (ie, the body of a cell)
                columns = vars(`Outlay Perct.`),      ## which col this refers to (note `vars()`)
                rows = `Outlay Perct.` >= .6)) %>%   ## the argument   ## using Q2 colors here
    #tab_style(style = cell_fill(color = "#5bb5d5"),
     #         locations = cells_body(
      #          columns = vars(`Outlay Percentage`),
       #         rows = `Outlay Percentage` < .6)) %>% 
    tab_style(style = cell_fill(color ="#ff939a"  ),
              locations = cells_body(
                columns = vars(`Outlay Perct.`),
                rows = `Outlay Perct.` < .6)) %>% 
  # tab_style((cell_text(style = "italic") ),
   #           locations = cells_body(
    #            columns = everything(),
     #           rows = 1))%>%
 tab_header(title = "USAID Mechanisms with 60% or Higher Outlay Rates") %>% 
  tab_source_note("Source: USAID Phoenix Financial System May 2021")%>%
  tab_footnote(footnote = "Includes new funding and applied pipeline.",
    locations = cells_column_labels(columns = "COP 20 Budget"))%>%
  
  tab_footnote(
    footnote = "Over-outlay due to increase of activities and TEC increase action approved in Q3 FY21.",
    locations = cells_body(columns = "Mechanism Name", rows = 2))%>%
  
  tab_footnote(
    footnote = "Over-outlay due to delayed payments from previous FY.",
    locations = cells_body(columns = "Mechanism Name", rows = 1))%>%
  

   tab_style(
    style = cell_borders(
      sides = "right",
      weight = px(1.5),
    ),
    locations = cells_body(
      columns = everything(),
      rows = everything()
    ))

```
tbl3%>%gtsave("high outlay table.png")


```{r}
#top 5 over outlay
tbl4<-df_Over %>%
   dplyr::select(-`Prime Partner Name`,-Mechanism.ID, -`Undisbursed`)%>%
  dplyr::relocate(`COP 20 Budget`, .after = `Total Outlays`)%>%
  arrange(desc(`Outlay Perct.`))%>%
 # top_n(6)%>%# sort by outlay %
  gt()%>%
  fmt_missing(columns = everything(),
            missing_text = "-")%>%
  fmt_percent(
   columns = vars(`Outlay Perct.`),
  decimals = 0)%>%
   fmt_currency( # add dolar signs
    columns = vars(`COP 20 Budget`, "Q1 Outlays", "Q2 Outlays", `Total Outlays`),
    decimals = 0,
    currency = "USD")%>%
  
   tab_options(
    table.font.names = "Source Sans Pro"
    ) %>% 
   cols_width(
    everything() ~ px(110))%>%
    tab_spanner(
    label = "COP20 Outlays",
    columns = c( "Q1 Outlays", "Q2 Outlays","Total Outlays"))%>%
  
  tab_style(style = cell_fill(color ="#ffcaa2"),      ## defining the what (the 4th value of the pal object)
              locations = cells_body(                 ## telling it where (ie, the body of a cell)
                columns = vars(`Outlay Perct.`),      ## which col this refers to (note `vars()`)
                rows = `Outlay Perct.` >= .6)) %>%   ## the argument   ## using Q2 colors here
    #tab_style(style = cell_fill(color = "#5bb5d5"),
     #         locations = cells_body(
      #          columns = vars(`Outlay Percentage`),
       #         rows = `Outlay Percentage` < .6)) %>% 
    tab_style(style = cell_fill(color ="#ff939a"  ),
              locations = cells_body(
                columns = vars(`Outlay Perct.`),
                rows = `Outlay Perct.` < .6)) %>% 
  # tab_style((cell_text(style = "italic") ),
   #           locations = cells_body(
    #            columns = everything(),
     #           rows = 1))%>%
 tab_header((title = "USAID's Over-Outlaying Mechanisms"),
 subtitle = ("Mechanisms Outlaying More than 60% as of Q2")
  )%>%
  tab_source_note("Source: USAID Phoenix Financial System May 2021")%>%
  tab_footnote(footnote = "Includes new funding and applied pipeline.",
    locations = cells_column_labels(columns = "COP 20 Budget"))%>%
  
#  tab_footnote(
 #   footnote = "Over-outlay due to increase of activities and TEC increase action approved in Q3 FY21.",
  #  locations = cells_body(columns = "Mechanism Name", rows = 2))%>%
  
#  tab_footnote(
 #   footnote = "Over-outlay due to delayed payments from previous FY.",
  #  locations = cells_body(columns = "Mechanism Name", rows = 1))%>%
#  tab_footnote(
 #   footnote = "ECHO under-outlay due to delayed vouchering and submission of payments.",
  #  locations = cells_body(columns = "Mechanism Name", rows = 6))%>%
  

   tab_style(
    style = cell_borders(
      sides = "right",
      weight = px(1.5),
    ),
    locations = cells_body(
      columns = everything(),
      rows = everything()
    ))
```
tbl4%>%gtsave("Over outlay table.png")




